version: "3.8"
services:
  app:
    env_file:
      - ./ki-kiyos-credential/envs/kiyos/staging/.env
    container_name: "kiyos"
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./:/app
    ports:
      - "8080:${PORT:-8080}"
    environment:
      PORT: ${PORT:-8080}
      TZ: Asia/Tokyo
    tty: true
    stdin_open: true
