name: test

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        type: choice
        description: デプロイする環境
        options:
        - staging
        - production

jobs:
  build_and_push:
    name: test job
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.inputs.targetEnv}}
